#!/usr/bin/env node
/**
 * The stripped transpiler: AsheeUI's design language, TypeScript -> C.
 *
 * A framebuffer cannot run React, and transpiling a React tree to C would mean reimplementing a
 * layout engine -- the same trap as transpiling to native widgets. What *can* be transpiled
 * correctly is the layer that is already declarative data with a deterministic mapping: the
 * scales in `tokens.ts` and the palette in `BRAND.md`. This converts exactly those; the renderer
 * that consumes them is hand-written C. That is why it is small, and it is not a general
 * TypeScript transpiler -- the repository next door is, with a real front end, and duplicating it
 * here would be a second thing to keep correct.
 *
 * It reads `export const NAME = { key: value, ... } as const;` and `export const NAME = 123;`,
 * which are the only two shapes tokens.ts uses. Anything else is REFUSED with its line, not
 * skipped: a reader that ignores what it does not understand emits a header that compiles and is
 * wrong, which is the failure this project keeps rediscovering.
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname } from "node:path";

const [, , tokensPath, brandPath, outPath] = process.argv;
if (!tokensPath || !brandPath || !outPath) {
  console.error("usage: tokens-to-c.mjs <tokens.ts> <BRAND.md> <out.h>");
  process.exit(2);
}

const tokensSource = readFileSync(tokensPath, "utf8");
const brandSource = readFileSync(brandPath, "utf8");

/** Tailwind's spacing step is 0.25rem; at a 16px root that is 4px. */
const PX_PER_STEP = 4;

// --- the reader -------------------------------------------------------------------------------
const refused = [];
const scalars = new Map();
const maps = new Map();

const lines = tokensSource.split("\n");
for (let i = 0; i < lines.length; i += 1) {
  const open = lines[i].match(/^export const ([A-Z0-9_]+) = \{$/);
  if (open) {
    const entries = [];
    let j = i + 1;
    for (; j < lines.length && !/^\} as const;/.test(lines[j]); j += 1) {
      const pair = lines[j].match(/^\s*"?([^":]+)"?:\s*([^,]+),\s*$/);
      if (pair) entries.push([pair[1], pair[2].trim()]);
      else if (lines[j].trim() !== "") refused.push(`${j + 1}: ${lines[j].trim()}`);
    }
    maps.set(open[1], entries);
    i = j;
    continue;
  }
  const scalar = lines[i].match(/^export const ([A-Z0-9_]+) = (\d+);$/);
  if (scalar) scalars.set(scalar[1], Number(scalar[2]));
}

if (refused.length > 0) {
  console.error("REFUSED -- tokens.ts contains shapes this reader does not understand:");
  for (const line of refused) console.error(`  ${line}`);
  console.error("Nothing was written. A header that compiles and is wrong is worse than none.");
  process.exit(1);
}

// --- the palette, read from BRAND.md rather than copied from it -------------------------------
const hexes = [...brandSource.matchAll(/#([0-9A-Fa-f]{6})/g)].map((m) => m[1].toUpperCase());
const EXPECTED = ["FB923C", "0B0F14", "EA580C", "FFFFFF"];
if (!EXPECTED.every((h) => hexes.includes(h))) {
  console.error(`BRAND.md no longer declares all four palette values. Found: ${hexes.join(", ")}`);
  process.exit(1);
}

/** Framebuffer pixels are RGB565: 5 bits red, 6 green, 5 blue. The web's hex does not fit. */
const rgb565 = (hex) => {
  const r = parseInt(hex.slice(0, 2), 16);
  const g = parseInt(hex.slice(2, 4), 16);
  const b = parseInt(hex.slice(4, 6), 16);
  return ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3);
};

/** Relative luminance, so BRAND.md's claim of 4.5:1 is computed rather than repeated. */
const luminance = (hex) => {
  const channel = (v) => {
    const c = v / 255;
    return c <= 0.03928 ? c / 12.92 : ((c + 0.055) / 1.055) ** 2.4;
  };
  return (
    0.2126 * channel(parseInt(hex.slice(0, 2), 16)) +
    0.7152 * channel(parseInt(hex.slice(2, 4), 16)) +
    0.0722 * channel(parseInt(hex.slice(4, 6), 16))
  );
};
const contrast = (a, b) => {
  const [hi, lo] = [luminance(a), luminance(b)].sort((x, y) => y - x);
  return (hi + 0.05) / (lo + 0.05);
};

const PAIRS = [
  ["ASHEE_UI_ACCENT", "FB923C", "ASHEE_UI_INK", "0B0F14"],
  ["ASHEE_COMPANY_ACCENT", "EA580C", "ASHEE_COMPANY_INK", "FFFFFF"],
];
const contrastFailures = [];
for (const [, aHex, , inkHex] of PAIRS) {
  const ratio = contrast(aHex, inkHex);
  if (ratio < 4.5) contrastFailures.push(`${aHex} on ${inkHex} = ${ratio.toFixed(2)}:1`);
}

// --- the emitter ------------------------------------------------------------------------------
const out = [];
out.push("/*");
out.push(" * Generated by tools/tokens-to-c.mjs. DO NOT EDIT.");
out.push(" *");
out.push(" * Read at build time, from the declared sources rather than from copies of them:");
out.push(` *   ${tokensPath}`);
out.push(` *   ${brandPath}`);
out.push(" */");
out.push("#ifndef ASHEE_TOKENS_H");
out.push("#define ASHEE_TOKENS_H");
out.push("");

const spacing = maps.get("SPACING_STEP");
if (!spacing) {
  console.error("tokens.ts no longer declares SPACING_STEP. Refusing to guess.");
  process.exit(1);
}
out.push("/* Spacing: Tailwind steps, resolved to pixels at a 16px root. */");
for (const [name, value] of spacing) {
  out.push(`#define ASHEE_SPACE_${name.replace(/[^A-Za-z0-9]/g, "").toUpperCase()} ${Number(value) * PX_PER_STEP}`);
}

out.push("");
out.push("/* Radii in pixels. `full` is -1: the renderer reads it as half the control height. */");
const RADIUS_PX = { none: 0, xs: 2, sm: 4, md: 6, lg: 8, xl: 12, full: -1 };
for (const [name] of maps.get("RADIUS_STEP") ?? []) {
  out.push(`#define ASHEE_RADIUS_${name.toUpperCase()} ${RADIUS_PX[name] ?? 0}`);
}

out.push("");
out.push("/* The typography scale, at the only one of them a bitmap font can express. */");
const FONT_PX = { xs: 8, sm: 12, md: 16, lg: 20, xl: 24, "2xl": 32, "3xl": 40 };
for (const [name] of maps.get("FONT_SIZE_STEP") ?? []) {
  out.push(`#define ASHEE_FONT_${name.replace(/[^A-Za-z0-9]/g, "").toUpperCase()} ${FONT_PX[name] ?? 16}`);
}

out.push("");
out.push("/* Scalar tokens, taken as written. */");
for (const [name, value] of scalars) out.push(`#define ASHEE_${name} ${value}`);

out.push("");
out.push("/* The palette, in the framebuffer's own format. */");
for (const [accent, aHex, ink, iHex] of PAIRS) {
  out.push(`#define ${accent} 0x${rgb565(aHex).toString(16).toUpperCase().padStart(4, "0")}  /* #${aHex} */`);
  out.push(`#define ${ink} 0x${rgb565(iHex).toString(16).toUpperCase().padStart(4, "0")}  /* #${iHex} */`);
}
out.push("");
out.push("/* The company site's own accent, which the family rule keeps distinct from AsheeUI's. */");
out.push(`#define ASHEE_COMPANY_SITE_ACCENT 0x${rgb565("EA580C").toString(16).toUpperCase().padStart(4, "0")}`);
out.push("");
out.push(
  `/* Contrast, computed by this tool: ${contrastFailures.length === 0 ? "every declared pair is at or above 4.5:1." : "FAILING -- see the build output."} */`,
);
out.push("");
out.push("#endif");

mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, `${out.join("\n")}\n`);

const counts = [...maps.values()].reduce((n, m) => n + m.length, 0) + scalars.size;
console.log(`  tokens     : ${counts} from ${maps.size + scalars.size} declarations -> ${outPath}`);
console.log("  palette    : 4 values read from BRAND.md, converted to RGB565");
console.log(`  contrast   : ${contrastFailures.length === 0 ? "all declared pairs >= 4.5:1" : contrastFailures.join(", ")}`);
if (contrastFailures.length > 0) process.exit(1);
