/*
 * ashee-os -- generated by tools/build.mjs. DO NOT EDIT.
 *
 * Bundled from the AsheeUI shared layer, which depends on nothing, for a framebuffer.
 * The palette is read from BRAND.md at build time rather than copied, so the two cannot
 * disagree about what the accent is.
 */
#ifndef ASHEE_BUNDLE_H
#define ASHEE_BUNDLE_H

/* === tokens.ts === */
/* --- tokens: the design language's vocabulary --- */
#define ASHEE_SPACING_NONE 0
#define ASHEE_SPACING_XS 1
#define ASHEE_SPACING_SM 2
#define ASHEE_SPACING_MD 4
#define ASHEE_SPACING_LG 6
#define ASHEE_SPACING_XL 8
#define ASHEE_SPACING_2XL 12
typedef enum ashee_font_weight_t {
  ASHEE_FONT_WEIGHT_NORMAL, ASHEE_FONT_WEIGHT_MEDIUM, ASHEE_FONT_WEIGHT_SEMIBOLD, ASHEE_FONT_WEIGHT_BOLD
} ashee_font_weight_t;
typedef enum ashee_color_role_t {
  ASHEE_COLOR_ROLE_NONE, ASHEE_COLOR_ROLE_PRIMARY, ASHEE_COLOR_ROLE_SECONDARY, ASHEE_COLOR_ROLE_DANGER, ASHEE_COLOR_ROLE_WARNING, ASHEE_COLOR_ROLE_SUCCESS
} ashee_color_role_t;
typedef enum ashee_variant_t {
  ASHEE_VARIANT_SOLID, ASHEE_VARIANT_FADED, ASHEE_VARIANT_BORDERED, ASHEE_VARIANT_GHOST, ASHEE_VARIANT_UNDERLINED
} ashee_variant_t;
typedef enum ashee_size_t {
  ASHEE_SIZE_SM, ASHEE_SIZE_MD, ASHEE_SIZE_LG
} ashee_size_t;
#define ASHEE_MIN_TOUCH_TARGET 44
#define ASHEE_ELEVATION_LEVEL_NONE 0
#define ASHEE_ELEVATION_LEVEL_SM 1
#define ASHEE_ELEVATION_LEVEL_MD 2
#define ASHEE_ELEVATION_LEVEL_LG 3
#define ASHEE_BREAKPOINT_SM 640
#define ASHEE_BREAKPOINT_MD 768
#define ASHEE_BREAKPOINT_LG 1024
#define ASHEE_BREAKPOINT_XL 1280

/* Resolved for this target: steps to pixels, radii and type sizes to pixels. */
#define ASHEE_SPACE_NONE 0
#define ASHEE_SPACE_XS 4
#define ASHEE_SPACE_SM 8
#define ASHEE_SPACE_MD 16
#define ASHEE_SPACE_LG 24
#define ASHEE_SPACE_XL 32
#define ASHEE_SPACE_2XL 48
#define ASHEE_RADIUS_NONE 0
#define ASHEE_RADIUS_XS 2
#define ASHEE_RADIUS_SM 4
#define ASHEE_RADIUS_MD 6
#define ASHEE_RADIUS_LG 8
#define ASHEE_RADIUS_XL 12
#define ASHEE_RADIUS_FULL -1
#define ASHEE_FONT_XS 8
#define ASHEE_FONT_SM 12
#define ASHEE_FONT_MD 16
#define ASHEE_FONT_LG 20
#define ASHEE_FONT_XL 24
#define ASHEE_FONT_2XL 32
#define ASHEE_FONT_3XL 40

/* NOT EXPRESSIBLE HERE: FONT_WEIGHT declares 4 weights; this target renders 1. Every weight selects it. See ashee.matrix. */

/* === contracts.ts === */
/* --- contracts: what each component promises, which both platforms already agree on. */
/*     Satisfying these in C is the third implementation, not a rewrite of the others. */

typedef struct ashee_themed_t {
  int variant;  /* Variant */
  int color;  /* ColorRole */
  int size;  /* Size */
  int radius;  /* Radius */
} ashee_themed_t;

typedef struct ashee_text_t {
  const char * children;  /* string */
  int role;  /* | "display" | "heading-xl" | "heading-lg" | "heading-md" | "heading- */
  int tone;  /* ColorRole | "muted" | "default" */
  int align;  /* "left" | "center" | "right" */
  int truncate;  /* boolean */
} ashee_text_t;

typedef struct ashee_button_t {
  ashee_themed_t themed;
  const char * children;  /* string */
  int fullWidth;  /* boolean */
  int isDisabled;  /* boolean */
  int isLoading;  /* boolean */
  int onPress;  /* () => void */
} ashee_button_t;

typedef struct ashee_card_t {
  ashee_themed_t themed;
  const char * title;  /* string */
  const char * description;  /* string */
  const char * header;  /* React.ReactNode */
  const char * footer;  /* React.ReactNode */
  int isPressable;  /* boolean */
} ashee_card_t;

typedef struct ashee_stack_t {
  int direction;  /* "row" | "column" */
  int gap;  /* Space */
  int align;  /* "start" | "center" | "end" | "stretch" */
  int justify;  /* "start" | "center" | "end" | "between" */
  int wrap;  /* boolean */
} ashee_stack_t;

typedef struct ashee_badge_t {
  ashee_themed_t themed;
  const char * children;  /* string */
} ashee_badge_t;

typedef struct ashee_input_t {
  ashee_themed_t themed;
  const char * label;  /* string */
  const char * value;  /* string */
  const char * defaultValue;  /* string */
  const char * onChangeText;  /* (value: string) => void */
  const char * placeholder;  /* string */
  const char * description;  /* string */
  const char * message;  /* string */
  int status;  /* "default" | "error" | "warning" | "success" */
  int isDisabled;  /* boolean */
  int multiline;  /* boolean */
} ashee_input_t;


/* --- palette, in the framebuffer's own pixel format --- */
#define ASHEE_UI_ACCENT 0xFC87  /* #FB923C */
#define ASHEE_UI_INK 0x0862  /* #0B0F14 */
#define ASHEE_COMPANY_ACCENT 0xEAC1  /* #EA580C */
#define ASHEE_COMPANY_INK 0xFFFF  /* #FFFFFF */

#endif
