/*
 * Generated by tools/tokens-to-c.mjs. DO NOT EDIT.
 *
 * Read at build time, from the declared sources rather than from copies of them:
 *   /home/asheegaming/Documents/Ashee-Softworks/AsheeUI/ashee-ui/packages/shared/src/tokens.ts
 *   /home/asheegaming/Documents/Ashee-Softworks/my_new_folder/brand/BRAND.md
 */
#ifndef ASHEE_TOKENS_H
#define ASHEE_TOKENS_H

/* Spacing: Tailwind steps, resolved to pixels at a 16px root. */
#define ASHEE_SPACE_NONE 0
#define ASHEE_SPACE_XS 4
#define ASHEE_SPACE_SM 8
#define ASHEE_SPACE_MD 16
#define ASHEE_SPACE_LG 24
#define ASHEE_SPACE_XL 32
#define ASHEE_SPACE_2XL 48

/* Radii in pixels. `full` is -1: the renderer reads it as half the control height. */
#define ASHEE_RADIUS_NONE 0
#define ASHEE_RADIUS_XS 2
#define ASHEE_RADIUS_SM 4
#define ASHEE_RADIUS_MD 6
#define ASHEE_RADIUS_LG 8
#define ASHEE_RADIUS_XL 12
#define ASHEE_RADIUS_FULL -1

/* The typography scale, at the only one of them a bitmap font can express. */
#define ASHEE_FONT_XS 8
#define ASHEE_FONT_SM 12
#define ASHEE_FONT_MD 16
#define ASHEE_FONT_LG 20
#define ASHEE_FONT_XL 24
#define ASHEE_FONT_2XL 32
#define ASHEE_FONT_3XL 40

/* Scalar tokens, taken as written. */
#define ASHEE_MIN_TOUCH_TARGET 44

/* The palette, in the framebuffer's own format. */
#define ASHEE_UI_ACCENT 0xFC87  /* #FB923C */
#define ASHEE_UI_INK 0x0862  /* #0B0F14 */
#define ASHEE_COMPANY_ACCENT 0xEAC1  /* #EA580C */
#define ASHEE_COMPANY_INK 0xFFFF  /* #FFFFFF */

/* The company site's own accent, which the family rule keeps distinct from AsheeUI's. */
#define ASHEE_COMPANY_SITE_ACCENT 0xEAC1

/* Contrast, computed by this tool: FAILING -- see the build output. */

#endif
